---
infrastructure:
  enabled: true
prometheus:
  enabled: false
webhook:
  enabled: false
ksm:
  enabled: true
kubeEvents:
  enabled: false
logging:
  enabled: false

kube-state-metrics:
  tag: v2.0.0
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 32Mi
  volumeattachments: false
  validatingwebhookconfigurations: false
  mutatingwebhookconfigurations: false
  networkpolicies: false

newrelic-infrastructure:
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 150Mi
  eventQueueDepth: 3000
