---
infrastructure:
  enabled: true
prometheus:
  enabled: false
webhook:
  enabled: false
ksm:
  enabled: true
kubeEvents:
  enabled: false
logging:
  enabled: false

kube-state-metrics:
  # default_resources_are_now_set:https://github.com/newrelic/helm-charts/tree/newrelic-infrastructure-2.2.0/charts/newrelic-infrastructure#resources
  tag: v2.0.0
  volumeattachments: false
  validatingwebhookconfigurations: false
  mutatingwebhookconfigurations: false
  networkpolicies: false

newrelic-infrastructure:
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 150Mi
  eventQueueDepth: 3000
